site_name: Progressista
site_url: https://filipinascimento.github.io/progressista/
repo_name: filipinascimento/progressista
repo_url: https://github.com/filipinascimento/progressista
edit_uri: ""
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - search.highlight
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: orange
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Server: server.md
  - Configuration: configuration.md
  - Client: client.md
  - Runbook: runbook.md
  - Hosting: hosting.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - progressista
          options:
            docstring_style: sphinx
            docstring_section_style: list
            merge_init_into_class: true
            show_root_heading: true
            show_signature_annotations: true
            show_source: false
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
        - docs
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
